### PR TITLE
Add Apache-2.0 and Zlib license options.

### PR DESCRIPTION
**Pull request by Lokathor**
This PR adds the "rust standard" Apache-2.0 license as a license option, as well as the Zlib license because it's even more permissive than the MIT license. The MIT license is of course also still an option.

Being a change in license, this will need the following folks to agree:
* [x] Osspial
* [x] Didgy74
* [x] ryanisaacg
* [x] repi
* [x] msiglreith
* [x] dxenonb
* [x] aloucks
* [ ] LeshaInc
* [x] Dispersia

Closes https://github.com/rust-windowing/raw-window-handle/issues/41

### CODE REVIEW

**Comment by Lokathor** [comment]
And a ping to:
@Osspial
@Didgy74
@ryanisaacg
@repi
@msiglreith
@dxenonb
@aloucks
@LeshaInc
@Dispersia

**Comment by msiglreith** [comment]
Thumbs up enough :D?
otherwise,

I license past and future contributions under the 'MIT OR Apache-2.0 OR Zlib' license, allowing licensees to chose either at their option.

**Comment by aloucks** [comment]
I agree.

**Comment by dxenonb** [comment]
I approve of the change.

**Comment by Didgy74** [comment]
I approve.

**Comment by Lokathor** [comment]
@Osspial On the grounds that the only outstanding vote is from @LeshaInc, who seems to have disappeared from github without a way to email them a follow-up, and also since they only added the `Hash` derives, I think that you should now merge this.

**Pull request merged**
