### PR TITLE
Bump version to 0.5.0

### PR DESCRIPTION
**Pull request by kchibisov**
--

Note, I can't push to crates.io, just opening a PR.

### CODE REVIEW

**Comment by Lokathor** [comment]
yeah this is good.

Usually i use the `cargo-release` tool which also makes a tag in the repo and stuff. i can probably do that later today.

**Review by Lokathor — APPROVED** [review]

**Comment by maroider** [comment]
Is it feasible for us to do the "semver trick" again?

**Comment by kchibisov** [comment]
>Is it feasible for us to do the "semver trick" again? It would be nice to avoid ecosystem churn again.

I don't think there's a need to. The point is that we can likely make the crate stable with such api (though, I'd wait for rust to update its core, so we can remove cty dep and have zero dependencies).

Breaking it when we can break is better in my opinion. Since this migration will happen sooner or later, and in case of rust I'd suggest to make it sooner.

**Comment by Lokathor** [comment]
ctypes got stabilized in core::ffi like *this morning*, so we're very close to that

https://github.com/rust-lang/rust/pull/98315

**Comment by kchibisov** [comment]
That's nice, so it won't take long. I'd wait for the rust version with those stable variants to reach major linux distributions and update to it releasing the `v1.0.0` version.

**Comment by Lokathor** [comment]
Well that will hit stable in about 12 weeks.

How far behind "latest stable" are most major Linux variants?

**Comment by kchibisov** [comment]
>How far behind "latest stable" are most major Linux variants?

Like 2 version or more (if we talk about Ubuntu and friend). So we'd have like half a year...

Though, we're not in a rush here, maybe the current design would need adjustments and recent changes would cause issues, so take it as a time before stabilization.

**Pull request merged**
