### PR TITLE
Get ready for 0.4

### PR DESCRIPTION
**Pull request by Lokathor**
We've got some breaking changes building up and it's time to move to a 0.4

* [ ] TODO: There's some docs in the related PR from Thomcc that we should incorporate here.
* [ ] TODO: we need to rename ios to uikit and macos to appkit, since you can use the macos types on target_os="ios" (via catalyst) and the ios types on target_os!="ios" (tvos, for example)

---
* Closes https://github.com/rust-windowing/raw-window-handle/issues/63
* Closes https://github.com/rust-windowing/raw-window-handle/issues/60
* Closes https://github.com/rust-windowing/raw-window-handle/issues/58

### CODE REVIEW

**Comment by DJMcNab** [comment]
Maybe a better name for `TrustedRawWindowHandle` would be something like `StableRawWindowHandle` or similar, since the guarantee is that the inner handle won't be mutated.

**Comment by i509VCB** [comment]
I'm curious here, I've noticed some of the handles like macOS, Windows, Android and iOS use `Option<NonNull<c_void>>` while Wayland, XCB and Xlib still use `*mut c_void`. Is this inconsistency intentional or were those specific handles not changed yet to be in line with the other handles.

**Comment by Lokathor** [comment]
I think it was an accidental oversight.

However, I also think that it's a bad change in retrospect. Every pointer here can optionally be null, that's just a blanket rule. I think actually using Option<NonNull<c_void>> makes things less ergonomic though. Realistically, we'll probably want to undo that change before the next release.

**Comment by Lokathor** [comment]
Merging this partial progress, and the rest will be finished up in https://github.com/rust-windowing/raw-window-handle/pull/70

**Pull request merged**
